CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    login text NOT NULL,
    password text NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240522133307_Init', '9.0.0-preview.3.24172.4');

COMMIT;

